### ISSUE TITLE
позиціонування зеленого кружечка

### ISSUE THREAD

**Issue by pecourses** [KarinaMilko/CSS_HW#6]
https://github.com/KarinaMilko/CSS_HW/blob/4889a37703db0e4eba80a2409f10e536b2f5199b/CSS/assets/css/styles.css#L59
- круто, що потренувалися з позишнами 👍. Ми ще будемо їх тренувати на занятті, але до цієї картки підкажу плюси та мінуси наведеного підходу. Зараз завдяки `relative` місце в потоці лишається вільним, і ми рухаємо елемент відносно цього місця, тому у нас лишається порожнім місце, звідки кружечок пересунули:
![image](https://github.com/KarinaMilko/CSS_HW/assets/67504221/5900bdab-a7e0-4261-b330-6a42d8f0a031)
Зачасту буває зручнішим, щоб такого місця не лишалося, це буде `absolute`. І тоді ми будемо позиціонувати не відносно свого ж місця, а треба обрати контейнер, відносно якого буде зручно вказувати місце кружечка. Зручно було б позиціонувати відносно картинки, але в неї не можна вкладувати дочірні елементи, тому класично в таких випадках беруть зображення у обгортку, їх розміри співпадають, і якщо ми будемо відраховувати right та bottom відносно контейнера, то це все одно, що відносно зображення:
```html
      <div class="imgWrapper">
        <img
          class="userImg"
          src="./assets/images/cat for user card.jpeg"
          alt="user photo"
        />
        <div class="iconsMenu"><i class="fa-solid fa-check"></i></div>
      </div>
``` 
```css
.imgWrapper {
  position: relative; /* далі позиціонування кружечка-іконки буде відносно враппера */
  width: 100px;
  height: 100px;
}
.userImg {
  width: 100%; /* картинка за розміром як враппер */
  height: 100%;
  object-fit: cover;
  border-radius: 50%;
}

.iconsMenu {
  width: 30px;
  height: 30px;
  border-radius: 50%;
  color: white;
  background-color: #36c483;
  display: flex;
  justify-content: center;
  align-items: center;
  box-shadow: 3px 1px 1px #c0ebd8;
  position: absolute; /* відносно враппера */
  bottom: 5%;
  right: 5%;
}
```
