### ISSUE TITLE
дублювання коду

### ISSUE THREAD

**Issue by pecourses** [KarinaMilko/CSS_HW#7]
https://github.com/KarinaMilko/CSS_HW/blob/4889a37703db0e4eba80a2409f10e536b2f5199b/CSS/assets/css/styles.css#L106-L152
- іконки мають майже однакові налаштування, окрім кольору тла. В таких випадках виносять спільні налаштування в єдине спільне місце:
```css
.social-links-TW,
.social-links-Fb,
.social-links-G,
.social-links-Be {
  display: flex;
  justify-content: center;
  align-items: center;
  text-decoration: none;
  width: 30px;
  height: 30px;
  border-radius: 50%;
  color: white;
}
.social-links-TW {
  background-color: #58bbf8;
}

.social-links-Fb {
  background-color: #45629e;
}

.social-links-G {
  background-color: #fe8b75;
}

.social-links-Be {
  background-color: #377efe;
}
``` 
Таким чином і код стане коротшим і читатиметься легше, і при підтримці коду, якщо треба буде змінити якийсь параметр, наприклад, ширину/висоту, то зміни треба буде вносити тільки в 2-х рядках, а не в 8-ми, що значно знижує кількість потенційних помилок.
